feat: initial implementation
MapColonies/schemas pull request #1
Opened 2024-04-01 13:17 UTC by CptSchnitz

2024-04-05 13:18 UTC, shimoncohen requested changes

2024-04-05 13:18 UTC, shimoncohen commented on scripts/validate.ts
> +      // the correct structure is is either only directories or only files, so if its not a file at this stage, it is an error
Remove duplicate `is`.

2024-04-07 12:20 UTC, CptSchnitz commented on README.md
> +- `x-populate-as-env` - ***experimental*** Whether to place the value into the environment variable defined in `x-env-value`.
If the env is defined, nothing would happen.

2024-04-07 12:20 UTC, CptSchnitz commented on README.md
> +- The files in the folders are in ascending order (v1,v2,v3,...).
We do check there is no skipping, its to keep order and consistency.

2024-04-07 12:24 UTC, CptSchnitz commented on schemas/common/db/partial/v1.schema.json
> +  "required": ["ssl"],
host and `port` have default values so there is no need for them to be required.
`ssl` is required as i want `enabled`  to always have a value.
In more general sense, for now the schemas are temporary until we release the package for general use.

2024-04-07 12:25 UTC, CptSchnitz commented on schemas/common/db/partial/v1.schema.json
> +          }
The logic is to set the value of `enabled` to `false` unless its `true`.

2024-04-07 12:34 UTC, CptSchnitz commented on scripts/build.ts
> +  const schemaName = camelCase(directory.substring(7).replaceAll(path.sep, '_') + '_' + fileVersion);
changed to not be a magic number

2024-04-07 12:34 UTC, CptSchnitz commented on scripts/validate.ts
> +      // the correct structure is is either only directories or only files, so if its not a file at this stage, it is an error
removed

2024-04-07 12:34 UTC, CptSchnitz commented on README.md
> +- If the schema is in Typescript, it should have an default export that is a valid JSON Schema. For convenience, the package [typebox](https://github.com/sinclairzx81/typebox) is installed to help ge
removed

2024-04-07 12:47 UTC, shimoncohen commented on README.md
> +- `x-populate-as-env` - ***experimental*** Whether to place the value into the environment variable defined in `x-env-value`.
Ok.

2024-04-07 12:47 UTC, shimoncohen commented on README.md
> +- The files in the folders are in ascending order (v1,v2,v3,...).
Ok, I don't see a problem with that currently.

2024-04-07 12:48 UTC, shimoncohen commented on schemas/common/db/partial/v1.schema.json
> +  "required": ["ssl"],
Ok, sounds good anyway.

2024-04-07 12:48 UTC, shimoncohen commented on schemas/common/db/partial/v1.schema.json
> +          }
Sounds good!

2024-04-07 12:49 UTC, shimoncohen commented on scripts/build.ts
> +  const schemaName = camelCase(directory.substring(7).replaceAll(path.sep, '_') + '_' + fileVersion);
Great :)

2024-04-07 12:49 UTC, shimoncohen approved these changes

2024-04-07 14:57 UTC, syncush approved these changes

2024-04-08 07:16 UTC, merged