feat: add job manager schema
MapColonies/schemas pull request #33
Opened 2024-09-09 14:22 UTC by netanelC

2024-09-10 08:05 UTC, CptSchnitz requested changes
1. We need approval from all job-managers users
2. consider splitting job creator and worker

2024-09-10 08:05 UTC, CptSchnitz commented on schemas/infra/jobManager/forClients/v1.schema.json
> +          "x-env-value": "TASK_MAX_ATTEMPTS"
add validation

2024-09-10 08:05 UTC, CptSchnitz commented on schemas/infra/jobManager/forClients/v1.schema.json
> +        "pingingIntervalTime": {
name should include milliseconds

2024-09-15 07:21 UTC, netanelC commented on schemas/infra/jobManager/forClients/v1.schema.json
> +        "pingingIntervalTime": {
Added

2024-09-15 08:00 UTC, CptSchnitz requested changes
The difference between SDK and worker is not explained at all. We need better names as worker is also type of sdk

2024-09-15 08:00 UTC, CptSchnitz commented on schemas/infra/jobManager/job/v1.schema.json
> +      "x-env-value": "JOB_TYPES"
you can't use ENV for array for now

2024-09-15 08:00 UTC, CptSchnitz commented on schemas/infra/jobManager/job/v1.schema.json
> +      },
add validation so there are no duplicates

2024-09-15 08:00 UTC, CptSchnitz commented on schemas/infra/jobManager/task/v1.schema.json
> +      "x-env-value": "TASK_TYPES"
same comment as for job

2024-09-15 08:00 UTC, CptSchnitz commented on schemas/infra/jobManager/sdk/v1.schema.json
> +        },
needs its own schema for reuse

2024-09-15 09:29 UTC, netanelC commented on schemas/infra/jobManager/forClients/v1.schema.json
> +          "x-env-value": "TASK_MAX_ATTEMPTS"
Added

2024-09-15 09:37 UTC, netanelC commented on schemas/infra/jobManager/sdk/v1.schema.json
> +        },
Added base schema

2024-09-15 10:20 UTC, netanelC commented on schemas/infra/jobManager/job/v1.schema.json
> +      "x-env-value": "JOB_TYPES"
Fixed

2024-09-15 11:33 UTC, CptSchnitz approved these changes

2024-09-15 12:52 UTC, merged