feat: default configs
MapColonies/schemas pull request #48
Opened 2024-11-26 07:03 UTC by CptSchnitz

2024-12-09 18:16 UTC, netanelC requested changes
The checks do not validate  the extension of the config file (for example: "jso" instead of "json"), only the schema.

2024-12-11 05:23 UTC, CptSchnitz commented on README.md
> +2. Checks that the configs file is valid.
there are multiple configs in the file..

2024-12-11 05:23 UTC, CptSchnitz commented on scripts/build.mts
> +  // }
no

2024-12-11 05:26 UTC, CptSchnitz commented on scripts/validate/validate.mts
its literally what it does, its the main entrypoint to all validations, just its less recommended to call file index.

2024-12-11 05:36 UTC, CptSchnitz commented
fixed not checking file extensions for the configs.

2024-12-11 06:26 UTC, netanelC commented on scripts/validate/validate.mts
OK

2024-12-11 06:32 UTC, netanelC commented on scripts/build.mts
> +  // }
yes. Oy Vaavoy

2024-12-11 07:56 UTC, netanelC approved these changes

2024-12-19 07:43 UTC, merged